# Generated by Django 4.2.1 on 2023-06-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOG_LOCATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=130)),
                ('address', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=15)),
                ('coord_lat', models.FloatField()),
                ('coord_lon', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ENTITY_USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=105)),
                ('first_name', models.CharField(max_length=105, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('auth_provider', models.CharField(default=None, max_length=120, null=True)),
                ('default_lang', models.CharField(blank=True, default='EN-GB', max_length=60, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('accept_tos', models.BooleanField(default=False, null=True)),
                ('fk_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capp.log_location')),
            ],
        ),
    ]
